### PR TITLE
Create c-cpp.yml

### PR DESCRIPTION
**Pull request by sam9306**
[misc.txt](https://github.com/SIDDK24/device_xiaomi_nabu/files/11231186/misc.txt)
[NOTICE.txt](https://github.com/SIDDK24/device_xiaomi_nabu/files/11231187/NOTICE.txt)
[README.md](https://github.com/SIDDK24/device_xiaomi_nabu/files/11231190/README.md)
rec_TWRP

### CODE REVIEW

**Comment by sam9306** [comment]
[4953bb5](https://github.com/SIDDK24/device_xiaomi_nabu/pull/2/commits/4953bb53c706fb60cdf041ae1c753880be60b8da)

**Comment by sam9306** [comment]
Git clone

**Comment by sam9306** [comment]
.patch

**Comment by sam9306** [comment]
.diff

**Comment by SIDDK24** [comment]
is the pr for CI???

**Comment by SIDDK24** [comment]
CI compiler not needed

**Pull request closed without merging**
